# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iov' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iov
  pod 'Alamofire', '~> 5.7.1' #网络请求
  pod 'JPush' #极光推送
  pod 'Kingfisher' #网络图片加载缓存
  pod 'MBProgressHUD' #加载动效
  pod 'RealmSwift' #本地数据库
  pod 'RxSwift' #响应式框架
  pod 'SwiftyJSON' #JSON数据解析

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
